config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#homepage'
  get 'homepage', to: 'home#homepage'
  get 'dashboard', to: 'home#dashboard'

  resources :entries
  resources :articles do 
    resources :comments
  end
  get "test", to: 'test#index'
  
  get "about", to: 'test#about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }

  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/entry.rb
class Entry < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  http_basic_authenticate_with name: "dhh", password: "secret", except:
[:index, :show]

  def index
   @articles=Article.all
  end

  def show
   @article = Article.find(params[:id])
  end

  def new
   @article=Article.new
  end

  def create
   @article = Article.new(article_params)

    if @article.save
     redirect_to articles_path
    else
     render :new, status: :unprocessable_entity
    end
  end

  def edit
   @article = Article.find(params[:id])
  end

  def update
   @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
   @article = Article.find(params[:id])
   @article.destroy

    redirect_to articles_path, status: :see_other
  end

  private
   def article_params
    params.require(:article).permit(:title, :body)
   end
end

app/controllers/comments_controller.rb
  class CommentsController < ApplicationController

    http_basic_authenticate_with name: "dhh", password: "secret", only:
  :destroy

    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      redirect_to article_path(@article)
    end

    def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_path(@article), status: 303
    end
  
    private
      def comment_params
        params.require(:comment).permit(:commenter, :body)
      end
  end
  

app/controllers/entries_controller.rb
class EntriesController < ApplicationController  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:passenger_name, :age, :ticket_amount, :temperature, :seats)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :authenticate_user!, only: %i[homepage]
  def homepage
  

  end

  def dashboard
  
  end

end  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.order(created_at: :desc)
    @posts = policy_scope(Post).order(created_at: :desc)
    authorize @posts
  end

  def show
  end
  def new
    @post = Post.new
  end
  def edit
  end
  def create
    @post = Post.new(post_params)
    if @post.save
      current_user.add_role :creator, @post
      redirect_to @post, notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end
  def update
    if @post.update(post_params)
      current_user.add_role :editor, @post
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @post.destroy
    redirect_to posts_url, notice: "Post was successfully destroyed."
  end
  private
    def set_post
      @post = Post.find(params[:id])
    end
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
def index

end
def about
  
end
end

app/controllers/test_file.rb
puts "hh"




#$, = ", "
# months = Hash.new( "month" )
months = {"1" => "January", "1" => "February"}

keys = months.keys

puts "#{keys}"

def myfunction(name,age)
return ("your name is "+ name + "  and age is "+age.to_s), 40,"another"
puts "hekkoo"
end

myfunction("ali",75)[2]

app/controllers/test_file_controller.rb
puts "hh"




#$, = ", "
# months = Hash.new( "month" )
months = {"1" => "January", "1" => "February"}

keys = months.keys

puts "#{keys}"

def myfunction(name,age)
return ("your name is "+ name + "  and age is "+age.to_s), 40,"another"
puts "hekkoo"
end

myfunction("ali",75)[2]

app/controllers/users_controller.rb
class UserController < ApplicationController
  def index
    @users = User.order(created_at: :desc)
    authorize @users
    # if current_user.has_any_role? :admin, :newuser
    #   @users = User.order(created_at: :desc)
    # else
    #   redirect_to root_path, alert: 'not authrized'
    # end
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update(user_params)
      redirect_to users_url, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def index
    @users = User.order(created_at: :desc)
  end

  private
    def user_params
      params.require(:user).permit({role_ids: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>
<%= link_to "Back to home", articles_path%>

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
    
    <%= link_to article.title, article %>
    </li>
  <% end %>
<%= link_to "New Article", new_article_path %>  
</ul>

app/views/articles/new.html.erb
<h1>New Article</h1>



<%= render "form", article: @article %>


app/views/articles/show.html.erb

<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>

  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
  </li>
</ul>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
    
  </p>
<% end %>




<h2>Add a comment:</h2>
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>


<%= link_to "Back to home", articles_path%>

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>">
  <p>
    <strong>Passenger name:</strong>
    <%= entry.passenger_name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= entry.age %>
  </p>

  <p>
    <strong>Ticket amount:</strong>
    <%= entry.ticket_amount %>
  </p>

  <p>
    <strong>Temperature:</strong>
    <%= entry.temperature %>
  </p>

  <p>
    <strong>Seats:</strong>
    <%= entry.seats %>
  </p>

</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :passenger_name, style: "display: block" %>
    <%= form.text_field :passenger_name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :ticket_amount, style: "display: block" %>
    <%= form.number_field :ticket_amount %>
  </div>

  <div>
    <%= form.label :temperature, style: "display: block" %>
    <%= form.number_field :temperature %>
  </div>

  <div>
    <%= form.label :seats, style: "display: block" %>
    <%= form.number_field :seats %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Show this entry", @entry %> |
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/entries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Entries</h1>

<div id="entries">
  <% @entries.each do |entry| %>
    <%= render entry %>
    <p>
      <%= link_to "Show this entry", entry %>
    </p>
  <% end %>
</div>

<%= link_to "New entry", new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/entries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entry %>

<div>
  <%= link_to "Edit this entry", edit_entry_path(@entry) %> |
  <%= link_to "Back to entries", entries_path %>

  <%= button_to "Destroy this entry", @entry, method: :delete %>
</div>

app/views/home/dashboard.html.erb
dashboard

app/views/home/homepage.html.erb
<h1>homepage</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <%= current_user.email %>
      <%= link_to 'Log Out', destroy_user_session_path, method: :delete %><br>
      <%= link_to 'Account Settings', edit_user_registration_path%>
    <% else %>
      <%= link_to 'Log In', new_user_session_path %>
      <%= link_to 'Sign Up', new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= @user.email %>
<%= form_with(model: @user) do |form| %>
  <%= form.collection_check_boxes :role_ids, Role.all, :id, :name %>
  <%= form.collection_check_boxes :role_ids, Role.where(resource_type: nil), :id, :name %>
  <%= @user.errors[:roles] %>
  <%= form.button :submit %>
<% end %> 

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= user.email %>
  <%= user.roles.pluck(:name) %>
  <%= link_to 'Edit roles', edit_user_path(user) %>
  <b>current user can see users index?</b>
  <%= policy(User).index? %>
  <b>current user can edit a user?</b>
  <%= policy(User).edit? %>
  <%= link_to 'Edit roles', edit_user_path(user) if policy(User).edit? %>
  <%= user.posts.pluck(:id) %>
  <%= user.creator_posts.pluck(:id) %>
  <%= user.editor_posts.pluck(:id) %>
  <br>
<% end %>